version: '3.8'
services:
  web:
    build: .
    command: bash -c 'rm -f tmp/pids/server.pid && bundle exec rackup -p 3000 -o 0.0.0.0'
    depends_on:
      - redis
    env_file: .env
    volumes:
      - .:/app
    ports:
      - '3000:3000'

  redis:
    image: redis:6.0
    command: redis-server
    ports:
      - '6379:6379'

  sidekiq:
    build: .
    volumes:
      - .:/app
    depends_on:
      - redis
    command: bundle exec sidekiq -r ./application.rb

volumes:
  db_data:
